-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 17:05:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`collection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`comic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`comic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `buy_date` DATE NOT NULL,
  `cover` ENUM('hard', 'soft') NOT NULL,
  `condition` ENUM('broken', 'marked', 'good condition', 'new') NOT NULL,
  `id_collection` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comic_collection_idx` (`id_collection` ASC) VISIBLE,
  CONSTRAINT `fk_comic_collection`
    FOREIGN KEY (`id_collection`)
    REFERENCES `library`.`collection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
