-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 17:05:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET utf8 ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`coleccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`comic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`comic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_compra` DATE NOT NULL,
  `tapa` ENUM('blanda', 'dura') NOT NULL,
  `estado` ENUM('roto', 'marcado', 'buen estado', 'como nuevo') NOT NULL,
  `id_coleccion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comic_coleccion_idx` (`id_coleccion` ASC) VISIBLE,
  CONSTRAINT `fk_comic_coleccion`
    FOREIGN KEY (`id_coleccion`)
    REFERENCES `libreria`.`coleccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
